=== AlwaysSayNo/distributed-systems/lab_7/src/main/resources/xml/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.grynko.nazar/study/department"
           xmlns="http://www.grynko.nazar/study/department"
           elementFormDefault="qualified">

    <xs:element name="department">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="group" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>

                        <xs:sequence>

                            <xs:element name="student" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>

                                    <xs:attribute name="id" type="xs:integer" use="required"/>
                                    <xs:attribute name="firstName" type="xs:string" use="required"/>
                                    <xs:attribute name="lastName" type="xs:string" use="required"/>
                                    <xs:attribute name="dateOfBirth" type="xs:string" use="required"/>

                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>

                        <xs:attribute name="id" type="xs:integer" use="required"/>
                        <xs:attribute name="subject" type="xs:string" use="required"/>

                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== AlwaysSayNo/distributed-systems/lab_7/src/main/resources/xml/input.xml
<department xmlns="http://www.grynko.nazar/study/department"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.grynko.nazar/study/department schema.xsd">

    <group id="0" subject="Mathematica">
        <student id="0" firstName="Nazar" lastName="Gray" dateOfBirth="22.02.2003"/>
        <student id="1" firstName="Nick" lastName="Black" dateOfBirth="19.12.2002"/>
        <student id="2" firstName="Anastasia" lastName="Yellow" dateOfBirth="20.04.2003"/>
        <student id="3" firstName="Sophia" lastName="White" dateOfBirth="11.05.2002"/>
    </group>

    <group id="1" subject="English">
        <student id="6" firstName="Nazar" lastName="Gray" dateOfBirth="22.02.2003"/>
        <student id="7" firstName="Nick" lastName="Black" dateOfBirth="19.12.2002"/>
        <student id="4" firstName="James" lastName="Brown" dateOfBirth="01.05.2002"/>
        <student id="5" firstName="Robert" lastName="Purple" dateOfBirth="12.11.2002"/>
    </group>

    <group id="2" subject="IT">
        <student id="8" firstName="Anastasia" lastName="Yellow" dateOfBirth="20.04.2003"/>
        <student id="9" firstName="James" lastName="Brown" dateOfBirth="01.05.2002"/>
        <student id="10" firstName="Robert" lastName="Purple" dateOfBirth="12.11.2002"/>
    </group>

</department>
